### ISSUE TITLE
Program stucked when handlling html.

### ISSUE THREAD

**Issue by nailchu** [gyakkun/qq-mht2html#1]
![image](https://user-images.githubusercontent.com/40136354/218404150-78b13246-f723-4b64-afa8-a0428cdd950a.png)

I tried several times and it always stopped at 24.53%.
My mht which was exported from QQ at 2023-02-07 is 1,368,503,553 bytes big.

**Comment by gyakkun** [comment]
Hi @zmz-zzzzz . Could you provide the following information:

* QQ version,
* QQ-MHT2HTML version.

Unfortunately the app doesn't export any log file. I may release a separated version for debugging later. Please wait.

**Comment by gyakkun** [comment]
Open #2 PR for the fix.

**Comment by gyakkun** [comment]
Hi @zmz-zzzzz , could you try the version below for the same input file? I've added some try-catch so that the line stukced should be skipped handling. If you don't mind could you please attach your log regarding to the problematic line here in this issue? Thank you.

https://github.com/gyakkun/qq-mht2html/releases/tag/v1.2.2

**Comment by nailchu** [comment]
Sorry for letting you wait! Version info below:
QQ 9.7.1.28934
qq-mht2html 1.2.1.0 

I tried the latest release just now. It didn't stop but the count of conversations seems wrong.
I use regex `.*消息对象:(.*?)</div>` then found 71 "消息对象:" but only 48 html files extracted.
![image](https://user-images.githubusercontent.com/40136354/218651786-70cf1fec-ef06-415e-8455-9d0b8ceb5326.png)

![image](https://user-images.githubusercontent.com/40136354/218651384-f9b50704-1205-497d-acb7-6bb2f343fec7.png)


Btw, didn't see `log` folder in `C:\Program Files\QQ Mht2html`. 🤷‍♂️
![image](https://user-images.githubusercontent.com/40136354/218651313-bee2f0b2-24f0-48a8-b4f5-e155f617010d.png)

**Comment by nailchu** [comment]
Could it be emoji reason?
Some conversations' title contain special emoji but Windows path may not support these characters.

For example, this conversation is not in output html files.
![image](https://user-images.githubusercontent.com/40136354/218657944-c13dbcab-9ee7-40cb-9a51-17e7fc3705d8.png)

**Comment by gyakkun** [comment]
> 

Hi @zmz-zzzzz , in terms of the absence of log file, have you re-run the program using the 1.2.2 version? Or could you launch the 1.2.2 version and just click start without setting any file location to see if any log files are generated? The location of logging file may vary across different environments of machines. The tool **[Everything](https://www.voidtools.com/)** may help. You can search `qq-mht2html.log` for the log file.

<img width="618" alt="qm_log" src="https://user-images.githubusercontent.com/5460071/218690058-ee9f6dd5-0386-4f61-897d-38f45b2c46de.png">

Emoji in title should be supported. My Windows version is 21H2 LTSC (19044.2486). May I know your Windows version?
<img width="533" alt="qm_emoji" src="https://user-images.githubusercontent.com/5460071/218690011-98f4b769-b4de-48ae-a643-f841b7510a57.png">

**Comment by nailchu** [comment]
Yes, I installed version 1.2.2-alpha and I have re-run it. 
I clicked "start" button but _Everything_ didn't found `qq-mht2html.log`.
OS version : Windows 10 Home 22H2 19045.2486

![image](https://user-images.githubusercontent.com/40136354/218731707-f23d6d22-3132-441a-a764-cbcc232f9fc4.png)

**Comment by gyakkun** [comment]
Hi @zmz-zzzzz , the log doesn't show up due to lack of write permission to `C:\Program Files`. You can install it in `D:\Program Files` or other disc or you can run it with Administrator permission.

**Comment by nailchu** [comment]
@gyakkun Hi.
Got the log! 
[qq-mht2html.log](https://github.com/gyakkun/qq-mht2html/files/10734622/qq-mht2html.log)

What about setting log folder to ` %APPDATA% ` ?

**Comment by gyakkun** [comment]
> @gyakkun Hi. Got the log! [qq-mht2html.log](https://github.com/gyakkun/qq-mht2html/files/10734622/qq-mht2html.log)
> 
> What about setting log folder to `%APPDATA%` ?

Hi @zmz-zzzzz . Judging from the log, it should be illegal character in filename or filename over maximum length in Windows. I do have some handling for filename sanitization but seems not adequate (https://github.com/gyakkun/qq-mht2html/blob/master/src/jvmMain/kotlin/Mht2Html.kt#L321-L327).

If you don't mind, could you provide some group / contact titles following the "消息对象"  regex above that have no output html files?  Along with the html output folder location, see if I can reproduce. Thank you.

**Comment by nailchu** [comment]
Hi @gyakkun 
Titles are in this file.
[match_lines.txt](https://github.com/gyakkun/qq-mht2html/files/10824733/match_lines.txt)

**Comment by gyakkun** [comment]
Hi @zmz-zzzzz . There're some control characters (0x11, "DC1") at line 47 of the txt file you provide. Have fixed it with a more strict sanitization for these special characters. Could you please check the latest version and see if it stucks again or lacks any files? Thank you very much for your support.

https://github.com/gyakkun/qq-mht2html/releases/tag/v1.2.3

**Comment by nailchu** [comment]
Hi @gyakkun . I tried the latest version. It didn't stuck and all conversations were extracted correctly.
Thank you for developping such useful tool. It helps a lot!
